### ISSUE TITLE
v44 kernel puts modules in /lib/modules/2.6.34-qtmoko-v34

### ISSUE THREAD

**Issue by ydirson** [radekp/qtmoko#122]
Looks like something we've seen in the past, no ?
Renaming the dir to match the running kernel does not help, incompatible module format.

Makes me wonder, is it sensible at all to upgrade the linux-image deb, when the kernel to boot is in a separate partition ?  Looks like upgrading this package is only meant to work for sdcard-based installations ?

**Comment by radekp** [comment]
There was wrong version in debian/config.gta02 this is fixed in v47
