### ISSUE TITLE
GPRS will not connect

### ISSUE THREAD

**Issue by Artox** [radekp/qtmoko#127]
I cant get GPRS to connect on my gta02 with qtmokov47(nor did I with v45). the settings(apn:internet, user:internet, pass:internet) works in SHR currently. but with qtmoko, when I click on the gprs connection and select "Start" form the menu, it switches to pending, then immediately offline again. GPRS used to work for me but I was in T-Mobile D1-Net before and now am in O2.

**Comment by ghost** [comment]
Same issue here. GPRS worked fine with v44 but not with v45 or v47. My mobile network has not changed (giffgaff), however in relation to the above comment, it does use the O2 network.

**Comment by radekp** [comment]
Hmm, i have again forgot to change auth->noauth in /etc/ppp/options Can you please try if that fixes it?

**Comment by Artox** [comment]
Almost magically it now works :)
(after changing the auth-line to noauth)

**Comment by radekp** [comment]
I am now reuploading also fixed v47 images then. Thanks for report and trying.
