### ISSUE TITLE
Alarms and events not triggered during suspend with v47 on the FreeRunner

### ISSUE THREAD

**Issue by ivaylo-valkov** [radekp/qtmoko#131]
When the FreeRunner is suspended, events with audible reminder and alarms are not triggered - visually and audibly. The phone wakes up at the correct time and the screen is turned on, but after that nothing happens. It stays like that for ~1-2 seconds and suspends again.

When the phone is not in suspend mode both alarms and events are triggered corectly.

**Comment by radekp** [comment]
This is fixed in v48. You just have to wait a few days until it's built and released

**Comment by ivaylo-valkov** [comment]
Thanks!
