### ISSUE TITLE
Building problems

### ISSUE THREAD

**Issue by prehistoricpenguin** [radekp/qtmoko#138]
I am sorry to report that i have undertook a problem.I build the latest versioin fllow the README in the source folder.But after excute the command "make install",I find problems like "recursive directory loop
" in the build folder.After the building,I found three more objects in my folder:the folder "build", folder "qtmoko_chroot" and a image file "qtmoko-chroot.img". And I neither know where is the rootfs I have build.Thanks for your reply!

**Comment by prehistoricpenguin** [comment]
[Modified]I use the command sequences below:
"
    git clone git://github.com/radekp/qtmoko.git
    cd qtmoko
    git submodule init
        git submodule update
    sudo scripts/qtmoko-chroot.sh 
    mkdir -p /root/qte/build
    cd /root/qte/build
    ../qtmoko/configure -device gta04
    make -j5 > /dev/null
        export LD_LIBRARY_PATH=/root/qte/build/qtopiacore/host/lib/
    make install
    exit
"
Thanks in advance!

**Comment by radekp** [comment]
Hi,
you are missing "git submodule update" and "export LD_LIBRARY_PATH=/root/qte/build/qtopiacore/host/lib/" lines. They are in the README.

Can you also please paste output?

**Comment by prehistoricpenguin** [comment]
I am so sorrry that I missed the two lines,but I have executed them.I have not seen some abnormal output during building and installing.And I am wondering how to get a rootfs from qtmoko.

**Comment by radekp** [comment]
It wont produce whole rootfs - just contents for /opt

Last command in the README is this: ../qtmoko/devices/gta04/scripts/update_qtmoko

It will create qtmoko_update.tar.gz (and if you have device connected it will also copy it to device and update it).

**Comment by radekp** [comment]
i hope i can close this...
