### ISSUE TITLE
Phone suspends if screen is locked - even while charging

### ISSUE THREAD

**Issue by schuma-gta02** [radekp/qtmoko#146]
The phone goes into suspend if the screen is locked - even if it is connected to external power.
The red LED goes off and the usb-interface is lost on PC then.

Using V48 on a GTA02.

**Comment by radekp** [comment]
This is not a bug. There are valid situations where you want this. First it's very useful if you want to fast charge the phone. The phone is suspended and nearly all the current goes from charger to battery. Besides suspending on charger is also needed for development...

**Comment by schuma-gta02** [comment]
OK. I did not know that. It was kind of unexpected to me, since I would have expected and did not find a configuration for this. Did I overlook something?

**Comment by radekp** [comment]
There is no config option for this. But you can e.g. launch nerongps and lock the screen and it will not suspend, because nerongps will keep the device awake.
