### ISSUE TITLE
Cannot remove something from the favorites

### ISSUE THREAD

**Issue by raigl** [radekp/qtmoko#148]
Adding something to the favorites is supported, but a GUI method to remove one could not be find.

**Comment by radekp** [comment]
Long press on the item brings up context menu where you can delete it. I hope it helps, if not feel free to reopen

**Comment by raigl** [comment]
Sorry, does not work on my system, no context menu arrives.
Is there any file to edit instead?

**Comment by Trim** [comment]
Hello,

You should do it from the application manager (short click on power button show it and select "Favorite" tab) and not from the homescreen star.

**Comment by raigl** [comment]
Short on the power button suspends, long gives options to restart / shutdown,
but no application manager. 
In the application manager (the rocket symbol in the main/home menu), the context menu (long hold)
only allows to add to the favorites and register for fast load, not to delete.
I am using a freshly installed v55 (debian).

**Comment by radekp** [comment]
On GTA02 you should use AUX to get to the right menu. During long press there should appear red circle and then the context menu

**Comment by radekp** [comment]
It should look like this http://scap.linuxtogo.org/files/a9bed6fb87a236142b15fcd0a0fe1b83.png

**Comment by raigl** [comment]
Got it finally: press AUX in the MAIN menu,
then there is different context menu in tapping long on the entry 
than the one in the lower left corner 
(see http://scap.linuxtogo.org/files/9572720a2879ce7175078874d6430fba.png,
which is missing on your picture).

Seems there is a need to write a short user guide to the new UI..

**Comment by Trim** [comment]
I just want to stress that being able to access task manager with power button is really useful for "one physical " phone because we can switch between applications despite withovt having aux button (I've recently broke my aux button). Why is it applied only to gta04 ?

**Comment by radekp** [comment]
Because AUX button has broken on my GTA04. I didnt want to change GTA02 behaviour because some people might be used to suspend phone with POWER button, but i guess they can learn to use lock button. I can apply the change for GTA02 too if you think it's useful.
