### ISSUE TITLE
 linux-image-2.6.34-qtmoko-gta02_v38 fails to configure

### ISSUE THREAD

**Issue by ydirson** [radekp/qtmoko#24]
Setting up linux-image-2.6.34-qtmoko-gta02 (v38-1) ...
WARNING: Couldn't open directory /lib/modules/2.6.34-qtmoko: No such file or directory
FATAL: Could not open /lib/modules/2.6.34-qtmoko/modules.dep.temp for writing: No such file or directory
dpkg: error processing linux-image-2.6.34-qtmoko-gta02 (--configure):
 subprocess installed post-installation script returned error exit status 1

Package installs modules into /lib/modules/2.6.34-qtmoko-v34/.

Adding a symlink allows to proceed with configuration, let's hope the next package upgrade will handle the symlink well...

**Comment by radekp** [comment]
On Sunday 05 February 2012 17:22:57 Yann Dirson wrote:

> Adding a symlink allows to proceed with configuration, let's hope the next
> package upgrade will handle the symlink well...

It should be ok now. You can try 

http://qtmoko.sourceforge.net/debian/linux-image-2.6.34-qtmoko-
gta02_v39-1_armel.deb

Regards

Radek

**Comment by ydirson** [comment]
Right, that one got fixed in v39-1
