### ISSUE TITLE
Microphone apparently not working on gta02

### ISSUE THREAD

**Issue by ydirson** [radekp/qtmoko#25]
Using mediarecorder I cannot get any sound to be recorded.  After playing with the mixer settings IIRC I could get past "getting empty wav files" situation (with time staying as 0:00 when requesting recording), and could get wav files with a duration, but no sound in them.

Then after googling I had a try at using the state file at http://docs.openmoko.org/trac/attachment/ticket/2477/working.state, and I'm now back the the "getting empty wav files" situation.

Playing a bit with "diff" I could determine that setting the 'Handset Mic Switch' flag to "true" is what allows to get the device unstuck.  Similarly, "arecord -t wav -d 5 /tmp/mon.wav" would block when the flag is false and record 0x80's when the flag is true.

Any idea what other settings to fiddle with ?

**Comment by guyou** [comment]
Something probably related to the bug discussed in list. Check the following workaround:
http://article.gmane.org/gmane.comp.handhelds.openmoko.community/61065

**Comment by ydirson** [comment]
Thanks, it does fix the problem

**Comment by ydirson** [comment]
Fix confirmed in v39-1.
