### ISSUE TITLE
-device neo -qvfb fails to build

### ISSUE THREAD

**Issue by ydirson** [radekp/qtmoko#43]
With my "translation" branch on github based on d05ac73ca4e1c2f05fb5231c630bc4a802b500aa (which does build for the device), the qvfb build fails with:

Project (/src/tools/qt/qvfb) WARNING: Skin ficgta01.skin exists in multiple locations:
  /work/yann/freerunner/qtmoko/qtmoko/devices/neo/ficgta01.skin
  /work/yann/freerunner/qtmoko/qtmoko/devices/gta04/ficgta01.skin
Project (/src/tools/qt/qvfb) ERROR: Terminated due to warnings
make: **\* [all] Aborted

**Comment by radekp** [comment]
On Tuesday 21 February 2012 07:55:51 Yann Dirson wrote:

> With my "translation" branch on github based on
> d05ac73ca4e1c2f05fb5231c630bc4a802b500aa (which does build for the
> device), the qvfb build fails with:
> 
> Project (/src/tools/qt/qvfb) WARNING: Skin ficgta01.skin exists in multiple
> locations: /work/yann/freerunner/qtmoko/qtmoko/devices/neo/ficgta01.skin
>   /work/yann/freerunner/qtmoko/qtmoko/devices/gta04/ficgta01.skin
> Project (/src/tools/qt/qvfb) ERROR: Terminated due to warnings
> make: **\* [all] Aborted

Hi,
can you try to rename the one in gta04 directory? E.g. to gta04.skin...

**Comment by ydirson** [comment]
Removed it, and the build does proceeed.
Rather than keeping it duplicate under another name, woudln't it be possible to refer to it as "../neo/ficgta01.skin" ?

**Comment by radekp** [comment]
I have renamed it for now - in case someone want to change the look.
